In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import numpy as np
a=np.array([9,3,4])
print(a)
b=np.array([90,23.1,"hii",True],dtype=object)
print(b)
c=np.array([True,False,True,False],dtype=int)
print(c)
d=np.array([[88,99],[23,34]])
print(d)
e=np.zeros((7,9),dtype=int)
print(e)
f=np.ones((8,6),dtype=int)
print(f)
g=np.arange(1,6,2)
print(g)
h=np.eye(3,4)
print(h)


[9 3 4]
[90 23.1 'hii' True]
[1 0 1 0]
[[88 99]
 [23 34]]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[1 3 5]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [3]:
import numpy as np
a=np.identity(8)
print(a)
b=np.full((5,5,),'qubits')
print(b)
c=np.random.seed(89)
print(c)
d=np.random.rand(5,7)
print(d)
e=np.random.randint(4,5)
print(e)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
[['qubits' 'qubits' 'qubits' 'qubits' 'qubits']
 ['qubits' 'qubits' 'qubits' 'qubits' 'qubits']
 ['qubits' 'qubits' 'qubits' 'qubits' 'qubits']
 ['qubits' 'qubits' 'qubits' 'qubits' 'qubits']
 ['qubits' 'qubits' 'qubits' 'qubits' 'qubits']]
None
[[0.49969432 0.25593713 0.25810063 0.09692171 0.56418511 0.01599007
  0.15259523]
 [0.48024773 0.09987276 0.41696389 0.91365081 0.35071951 0.11460437
  0.71260839]
 [0.10188615 0.40570044 0.66548144 0.13835937 0.83043309 0.12319969
  0.58779155]
 [0.06309849 0.49710274 0.92839462 0.80603084 0.19839124 0.34528354
  0.53473647]
 [0.97858347 0.5030445  0.3474475  0.21278653 0.17745402 0.1040286
  0.18745545]]
4


In [4]:
import numpy as np
a=np.array([[12,12,12],[1,5,78]],dtype=int)
print(a)
b=a.shape
print(b)
c=a.size
print(c)
d=a.ndim
print(d)
e=a.dtype
print(e)
print(a.itemsize)
f=np.empty([2,1])
print(f)

[[12 12 12]
 [ 1  5 78]]
(2, 3)
6
2
int64
8
[[1.52661348e+159]
 [3.78458586e-194]]


In [5]:
import numpy as np
a=np.array([[12,12,12],[1,5,78],[5,6,7]])
print(a)
print(a[0,1])
print(a[2])
print(a[:,1])


[[12 12 12]
 [ 1  5 78]
 [ 5  6  7]]
12
[5 6 7]
[12  5  6]


In [6]:
import numpy as np
a=np.array([[12,12,12],[1,5,78]])
print(a)
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())

[[12 12 12]
 [ 1  5 78]]
120
1
78
20.0


In [7]:
import numpy as np
a=np.array([[12,12,12],[1,5,78],[5,6,7]])
print(a)
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))

[[12 12 12]
 [ 1  5 78]
 [ 5  6  7]]
[[ 1  5  7]
 [ 5  6 12]
 [12 12 78]]
[[12 12 12]
 [ 1  5 78]
 [ 5  6  7]]
