In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import pandas as pd
a={"SI-No":[1,2,3],"Name":["Akshitha","Lavanya","Jyothi"],"Marks":[35,26,34]}
print(pd.DataFrame(a))
a=pd.Series(["cricket","players",1],index=[60,61,92])
print(pd.DataFrame(a))
a=pd.Series([1,6,10],["a","b","c"])
b=pd.DataFrame(a)
print(b)
print(type(b))
print(type(a))
print(a)
a=[1,2,3]
b=["Akshitha","Lavanya","Jyothi"]
c=[35,26,34]
print("SI-NO",a,"Name",b,"Marks",c)

   SI-No      Name  Marks
0      1  Akshitha     35
1      2   Lavanya     26
2      3    Jyothi     34
          0
60  cricket
61  players
92        1
    0
a   1
b   6
c  10
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
a     1
b     6
c    10
dtype: int64
SI-NO [1, 2, 3] Name ['Akshitha', 'Lavanya', 'Jyothi'] Marks [35, 26, 34]


In [3]:
a=pd.DataFrame({"si-no":[1,2,3,4,5],"name":["A","L","J","l","a"],"Marks":[35,26,34,39,56]})
print(a)
a[a["Marks"]>34]

   si-no name  Marks
0      1    A     35
1      2    L     26
2      3    J     34
3      4    l     39
4      5    a     56


,si-no,name,Marks
0,1,A,35
3,4,l,39
4,5,a,56


In [4]:
import pandas as pd
a=pd.Series([10,20,30,40,50])
print(a.mean())
print(a.max())
print(a.min())
print(a.unique())
print(a.values)
print(a.size)
print(a.dtype)
print(a.index)
print(a.name)

30.0
50
10
[10 20 30 40 50]
[10 20 30 40 50]
5
int64
RangeIndex(start=0, stop=5, step=1)
None


In [5]:
import pandas as pd
a=pd.Series([10,20,30,40,50],name="apples")
print(a.mean())
print(a.max())
print(a.min())
print(a.unique())
print(a.values)
print(a.size)
print(a.dtype)
print(a.index)
print(a.name)

30.0
50
10
[10 20 30 40 50]
[10 20 30 40 50]
5
int64
RangeIndex(start=0, stop=5, step=1)
apples


In [6]:
import pandas as pd
z=pd.DataFrame({"sports":["cricket","volleybaall","kho-kho","carooms","shettle"],
               "Ranking":[1,6,8,9,25],
               "prefrence":[6,8,7,1,2],
               "venue":["vskp","vsr","NLR","KDP","ELR"],})
print(z)
x=z.to_csv("sports.csv")
x=z.to_excel("sports.xlsx")
x=z.to_json("sports.json")
print(x)


        sports  Ranking  prefrence venue
0      cricket        1          6  vskp
1  volleybaall        6          8   vsr
2      kho-kho        8          7   NLR
3      carooms        9          1   KDP
4      shettle       25          2   ELR
None
