In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import torch 
a=torch.tensor([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.numel)
print(a.dtype)
print(a.device)
b=torch.ones(2,3,dtype=int)
print(b)
print(torch.zeros(2,3,dtype=torch.int64))

tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])
<built-in method numel of Tensor object at 0x7f2881d90280>
torch.int64
cpu
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [3]:
import torch
print(torch.rand(2,3))
print(torch.randn(2,3))

tensor([[0.0989, 0.3961, 0.2838],
        [0.7728, 0.9065, 0.1362]])
tensor([[ 0.1059, -0.1172,  0.9534],
        [-1.9129, -1.7937, -0.6920]])


In [4]:
import torch
a=torch.tensor([[10,12,13],[14,15,16],[17,18,19]])
print(a)
print(a[1])
print(a[2])
print(a[[1,2],1])
print(a[[0,1,2]])
print(a[0:3,0:1])
print(a[:3,0])
print(a[:,0])
print(a[2:,])

tensor([[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
tensor([14, 15, 16])
tensor([17, 18, 19])
tensor([15, 18])
tensor([[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
tensor([[10],
        [14],
        [17]])
tensor([10, 14, 17])
tensor([10, 14, 17])
tensor([[17, 18, 19]])


In [5]:
import torch
a=torch.tensor([[2,8,10],[7,8,6],[10,11,12]])
b=torch.tensor([[1,3,9],[6,7,8],[8,9,10]])
print(a.sum())
print(torch.sum(a))
print(torch.subtract(a,b))
print(torch.argmax(a))#index position
print(torch.argmin(a))
print(torch.multiply(a,b))
print(torch.divide(a,b))

tensor(74)
tensor(74)
tensor([[ 1,  5,  1],
        [ 1,  1, -2],
        [ 2,  2,  2]])
tensor(8)
tensor(0)
tensor([[  2,  24,  90],
        [ 42,  56,  48],
        [ 80,  99, 120]])
tensor([[2.0000, 2.6667, 1.1111],
        [1.1667, 1.1429, 0.7500],
        [1.2500, 1.2222, 1.2000]])


In [6]:
import torch
a=torch.tensor([70,36,27,50,99])
print(a[a>50])
print(a[a>34])
print(a[a<50])

tensor([70, 99])
tensor([70, 36, 50, 99])
tensor([36, 27])
