In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import torch
a=torch.tensor([1,2,3])
a.device
torch.cuda.is_available()

False

In [3]:
import tensorflow 
tensorflow.__version__

'2.20.0'

In [4]:
import tensorflow as tf
a=tf.constant(8)
print("\n",a)
b=tf.Variable(a)
print("\n",b)


 tf.Tensor(8, shape=(), dtype=int32)

 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=8>


2026-09-08 04:18:11.345800: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [5]:
import tensorflow
b=tf.constant([[3,4,5],[7,8,9]])
print("\n",b)
b=tf.Variable([[2,3,4],[5,6,7]])
print("\n",b)
d=b.assign([[7,6,5],[9,8,1]])
print(d)


 tf.Tensor(
[[3 4 5]
 [7 8 9]], shape=(2, 3), dtype=int32)

 <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[7, 6, 5],
       [9, 8, 1]], dtype=int32)>


In [6]:
import tensorflow
b=tf.range(3,16,3)
print("\n",b)
c=tf.fill([3,3],8)
print(c)
d=tf.zeros(3)
print(d)
d=tf.zeros([2,3])
print(d)
c=tf.ones(4)
print(c)
a=tf.ones([3,4])
print(a)


 tf.Tensor([ 3  6  9 12 15], shape=(5,), dtype=int32)
tf.Tensor(
[[8 8 8]
 [8 8 8]
 [8 8 8]], shape=(3, 3), dtype=int32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [7]:
import tensorflow as tf
a=tf.constant([[3,4,5],[8,7,6]])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(tf.size(a))


(2, 3)
2
<dtype: 'int32'>
tf.Tensor(6, shape=(), dtype=int32)


In [8]:
import tensorflow as tf
a=tf.constant([[3,4,5],[6,5,7],[8,7,6]])
print(a)
print(a[1,1])
print(a[0])
b=tf.transpose(a)
print(b)
print(a[2])


tf.Tensor(
[[3 4 5]
 [6 5 7]
 [8 7 6]], shape=(3, 3), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor(
[[3 6 8]
 [4 5 7]
 [5 7 6]], shape=(3, 3), dtype=int32)
tf.Tensor([8 7 6], shape=(3,), dtype=int32)


In [9]:
import tensorflow as tf
a=tf.constant([[3,4,5,7],[6,5,8,7],[8,9,7,6]])
print(a)
print(a[2:3])
print(a[2:3,0:4])
print(a[1:3,2:4])
print(a[0:2,1:3])
print(a[-1,-3])
print(a[-1:-2:-1,-3:-4:-1])

tf.Tensor(
[[3 4 5 7]
 [6 5 8 7]
 [8 9 7 6]], shape=(3, 4), dtype=int32)
tf.Tensor([[8 9 7 6]], shape=(1, 4), dtype=int32)
tf.Tensor([[8 9 7 6]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[8 7]
 [7 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[4 5]
 [5 8]], shape=(2, 2), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([[9]], shape=(1, 1), dtype=int32)


In [10]:
import tensorflow as tf
a=tf.constant([[3,4,5,7],[8,9,10,11],[12,13,14,15]])
b=tf.reverse(a,axis=[0])
print(b)
b=tf.reverse(a,axis=[1])
print(b)
b=tf.reverse(a,axis=[1,0])
print(b)
d=tf.reshape(a,(4,-1))
print(d)
d=tf.reshape(a,(-1))
print(d)


tf.Tensor(
[[12 13 14 15]
 [ 8  9 10 11]
 [ 3  4  5  7]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 7  5  4  3]
 [11 10  9  8]
 [15 14 13 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[15 14 13 12]
 [11 10  9  8]
 [ 7  5  4  3]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 3  4  5]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]], shape=(4, 3), dtype=int32)
tf.Tensor([ 3  4  5  7  8  9 10 11 12 13 14 15], shape=(12,), dtype=int32)


In [11]:
import tensorflow as tf
a=tf.constant([2,3,4])
b=tf.constant([6,7,8])
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))

tf.Tensor([ 8 10 12], shape=(3,), dtype=int32)
tf.Tensor([-4 -4 -4], shape=(3,), dtype=int32)
tf.Tensor([12 21 32], shape=(3,), dtype=int32)
tf.Tensor([0.33333333 0.42857143 0.5       ], shape=(3,), dtype=float64)
