In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import torch
a=torch.tensor([6,2,3])
print(a)
b=torch.tensor([[23,4,5],[6,7,8]])
print(b)
print(b.shape)#this is attribute
print(b.size())#this is size function
c=torch.tensor([9,3,8,7])
print(c.type())
d=torch.full((3,5),8)
print(d)
e=torch.empty(6)
print(e)
f=torch.zeros(2)
print(f)
g=torch.ones(4)
print(g)

tensor([6, 2, 3])
tensor([[23,  4,  5],
        [ 6,  7,  8]])
torch.Size([2, 3])
torch.Size([2, 3])
torch.LongTensor
tensor([[8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8]])
tensor([0.0000e+00, 0.0000e+00, 6.0867e-19, 0.0000e+00, 0.0000e+00, 0.0000e+00])
tensor([0., 0.])
tensor([1., 1., 1., 1.])


In [3]:
import torch
a=torch.arange(96,108)
print(a)
a=torch.arange(96,108,6)
print(a)
b=torch.eye(3,2)
print(b)
c=torch.tensor([514,460,588,720])
print(c[2])
print(c[1:3])
print(c[:])
print(c[-1])
print(c[-4])
print(c.numel())
c.device

tensor([ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107])
tensor([ 96, 102])
tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])
tensor(588)
tensor([460, 588])
tensor([514, 460, 588, 720])
tensor(720)
tensor(514)
4


device(type='cpu')

In [4]:
import torch
a=torch.tensor([1,2,3,4])
print(a.reshape(2,2))
print(a.reshape(-1,2))
print(a.reshape(1,4))
print(a.reshape(4,1))
b=torch.tensor([[[1,2,3,4],[5,6,7,8],[8,5,6,3]]])
print(b)
print(b.shape)
c=torch.tensor([[[1,2,3,4],[7,6,5,8]],[[23,45,56,67],[34,56,87,89]],[[3,4,5,6],[45,65,76,87]]])
print(c)
print(c.shape)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8],
         [8, 5, 6, 3]]])
torch.Size([1, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [ 7,  6,  5,  8]],

        [[23, 45, 56, 67],
         [34, 56, 87, 89]],

        [[ 3,  4,  5,  6],
         [45, 65, 76, 87]]])
torch.Size([3, 2, 4])


In [5]:
import torch
a=torch.tensor([[10,100,200],[300,400,500]])
print(a[1][1])#indexing
print(a[1:2,1:2])#slicing
print(a[1:3,2:3])
print(a[0:1,0:1])

tensor(400)
tensor([[400]])
tensor([[500]])
tensor([[10]])


In [6]:
import torch
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[7,8],[9,10],[11,12]])
print(torch.cat((a,b),dim=0))
print(torch.cat((a,b),dim=1))
print(torch.cat((a,b),dim=-2))
print(torch.cat((a,b),dim=-1))
a=torch.tensor([[3,5,4],[90,65,56],[23,45,36]])
b=torch.tensor([[79,83],[99,103],[110,86]])
print(torch.cat((a,b),dim=1))
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[7,8],[9,10]])
print(torch.cat((a,b),dim=0))

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10],
        [ 5,  6, 11, 12]])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10],
        [ 5,  6, 11, 12]])
tensor([[  3,   5,   4,  79,  83],
        [ 90,  65,  56,  99, 103],
        [ 23,  45,  36, 110,  86]])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])


In [7]:
import torch
a=torch.tensor([1,10,12,13,15,18])
print(torch.split(a,5))
print(torch.split(a,2))
print(torch.split(a,3))
b=torch.arange(20)
print(torch.split(b,[3,7,5,4,1,0]))
print(torch.chunk(b,3))
print(torch.chunk(b,4))
print(torch.chunk(b,5))
a=torch.zeros(4,5,6)
print(a)
print(a.size(1))
a=torch.ones(2,3,6)
print(a)
print(a.size(1))
a=[1,2,3,4,5]
print(a[2])

(tensor([ 1, 10, 12, 13, 15]), tensor([18]))
(tensor([ 1, 10]), tensor([12, 13]), tensor([15, 18]))
(tensor([ 1, 10, 12]), tensor([13, 15, 18]))
(tensor([0, 1, 2]), tensor([3, 4, 5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14]), tensor([15, 16, 17, 18]), tensor([19]), tensor([], dtype=torch.int64))
(tensor([0, 1, 2, 3, 4, 5, 6]), tensor([ 7,  8,  9, 10, 11, 12, 13]), tensor([14, 15, 16, 17, 18, 19]))
(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14]), tensor([15, 16, 17, 18, 19]))
(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]), tensor([12, 13, 14, 15]), tensor([16, 17, 18, 19]))
tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0

In [8]:
import torch
a=torch.tensor([[5,6,7],[8,9,10]],dtype=float)
print(a.sum())
print(a.sum(dim=0))
print(a.sum(dim=1))#column
print(a.mean())
print(a.mean(dim=0))
print(a.mean(dim=1))
print(a.max())
print(a.max(dim=0))
print(a.max(dim=1))
print(a.argmax())
print(a.argmin())


tensor(45., dtype=torch.float64)
tensor([13., 15., 17.], dtype=torch.float64)
tensor([18., 27.], dtype=torch.float64)
tensor(7.5000, dtype=torch.float64)
tensor([6.5000, 7.5000, 8.5000], dtype=torch.float64)
tensor([6., 9.], dtype=torch.float64)
tensor(10., dtype=torch.float64)
torch.return_types.max(
values=tensor([ 8.,  9., 10.], dtype=torch.float64),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([ 7., 10.], dtype=torch.float64),
indices=tensor([2, 2]))
tensor(5)
tensor(0)


In [9]:
import torch
a=torch.tensor([[10,4,3],[8,3,2]])
b=torch.tensor([[3,5],[4,8],[1,3]])
print(torch.matmul(a,b))#matrix multiplication
print(a@b)#multiplication

tensor([[49, 91],
        [38, 70]])
tensor([[49, 91],
        [38, 70]])


In [10]:
import torch
a=torch.tensor([1,2,3])
a.device
torch.cuda.is_available()

False